parameters:
#    dtb_offline.example.class: DTB\OfflineBundle\Example

services:
#    dtb_offline.example:
#        class: %dtb_offline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
