<?php

namespace DTB\BdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CandidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatureRepository extends EntityRepository
{
}
