<?php

namespace DTB\BdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaletteRepository extends EntityRepository
{
}
