<?php

namespace DTB\BdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends EntityRepository
{
}
