<?php

namespace DTB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilePictureRepository extends EntityRepository
{
}
