dtb_bd_create:
    pattern:  /createBD
    defaults: { _controller: DTBBdBundle:Default:create }
    
dtb_bd_explore:
    pattern:  /explore
    defaults: { _controller: DTBBdBundle:Explore:index }
    
dtb_bd_contribute:
    pattern:  /contribute
    defaults: { _controller: DTBBdBundle:Contribute:index }
    
dtb_bd_update:
    pattern:  /updateBD/{id}
    defaults: { _controller: DTBBdBundle:Default:update }

dtb_bd_show:
    pattern:  /showBD/{id}
    defaults: { _controller: DTBBdBundle:Default:show }
    
dtb_bd_show_planche:
    pattern:  /showPlanche/{id}
    defaults: { _controller: DTBBdBundle:Default:showPlanche }

dtb_bd_move_image:
    pattern:  /moveImage/{id}/{x}/{y}
    defaults: { _controller: DTBBdBundle:Default:moveImage }
    
dtb_bd_resize_image:
    pattern:  /resize/{id}/{x}/{y}
    defaults: { _controller: DTBBdBundle:Default:resizeImage }
    
dtb_bd_show_image:
    pattern:  /showImage/{id}
    defaults: { _controller: DTBBdBundle:Default:showImage }
    
dtb_bd_create_image:
    pattern: /createImage/{id}
    defaults: { _controller: DTBBdBundle:Default:createImage }
    
dtb_bd_add_planche:
    pattern:  /addPlanche/{id}
    defaults: { _controller: DTBBdBundle:Default:addPlanche }
    
dtb_bd_candidate_drawer:
    pattern:  /candidateDrawer/{id}
    defaults: { _controller: DTBBdBundle:Candidate:drawer }
    
dtb_bd_candidate_scenarist:
    pattern:  /candidateScenarist/{id}
    defaults: { _controller: DTBBdBundle:Candidate:scenarist }
    
dtb_bd_see_candidatures:
    pattern:  /seeCandidates/{id}
    defaults: { _controller: DTBBdBundle:Candidate:see }
    
dtb_bd_validate_candidature:
    pattern:  /validateCandidate/{id}
    defaults: { _controller: DTBBdBundle:Candidate:validate }
    
dtb_bd_delete_candidature:
    pattern:  /deleteCandidate/{id}
    defaults: { _controller: DTBBdBundle:Candidate:delete }

dtb_bd_show_scenario:
    pattern:  /showScenario/{id}
    defaults: { _controller: DTBBdBundle:Default:showScenario }
    
dtb_bd_edit_scenario:
    pattern:  /editScenario/{id}
    defaults: { _controller: DTBBdBundle:Default:editScenario }
    
dtb_bd_redirect_planche:
    pattern:  /redirectPlanche/{page}/{bd}
    defaults: { _controller: DTBBdBundle:Default:redirectPlanche }
    
dtb_bd_save_scenario:
    pattern:  /saveScenario/{id}
    defaults: { _controller: DTBBdBundle:Default:saveScenario }
    
dtb_bd_save_image:
    pattern:  /saveImage/{id}
    defaults: { _controller: DTBBdBundle:Default:saveImage }

dtb_bd_get_image:
    pattern:  /getImage/{id}
    defaults: { _controller: DTBBdBundle:Default:getImage }
    
dtb_show_board:
    pattern: /showBoard/{id}
    defaults: { _controller: DTBBdBundle:Forum:show }
    
dtb_show_forum:
    pattern: /showForum/{id}
    defaults: { _controller: DTBBdBundle:Forum:showForum }

dtb_show_topic:
    pattern: /showTopic/{id}
    defaults: { _controller: DTBBdBundle:Forum:showTopic }
    
dtb_create_topic:
    pattern: /createTopic/{id}
    defaults: { _controller: DTBBdBundle:Forum:createTopic }
    
dtb_create_post:
    pattern: /createPost/{id}
    defaults: { _controller: DTBBdBundle:Forum:createPost }
    
dtb_update_topic:
    pattern: /updateTopic/{id}
    defaults: { _controller: DTBBdBundle:Forum:updateTopic }
    
dtb_update_post:
    pattern: /updatePost/{id}
    defaults: { _controller: DTBBdBundle:Forum:updatePost }
    
dtb_delete_topic:
    pattern: /deleteTopic/{id}
    defaults: { _controller: DTBBdBundle:Forum:deleteTopic }
    
dtb_delete_post:
    pattern: /deletePost/{id}
    defaults: { _controller: DTBBdBundle:Forum:deletePost }