dtb_bd_create:
    pattern:  /createBD
    defaults: { _controller: DTBBdBundle:Default:create }
    
dtb_bd_explore:
    pattern:  /explore
    defaults: { _controller: DTBBdBundle:Explore:index }
    
dtb_bd_contribute:
    pattern:  /contribute
    defaults: { _controller: DTBBdBundle:Contribute:index }
    
dtb_bd_update:
    pattern:  /updateBD/{id}
    defaults: { _controller: DTBBdBundle:Default:update }

dtb_bd_show:
    pattern:  /showBD/{id}
    defaults: { _controller: DTBBdBundle:Default:show }

dtb_bd_add_planche:
    pattern:  /addPlanche/{id}
    defaults: { _controller: DTBBdBundle:Default:addPlanche }
    
dtb_bd_candidate_drawer:
    pattern:  /candidateDrawer/{id}
    defaults: { _controller: DTBBdBundle:Candidate:drawer }
    
dtb_bd_candidate_scenarist:
    pattern:  /candidateScenarist/{id}
    defaults: { _controller: DTBBdBundle:Candidate:scenarist }
    
dtb_bd_see_candidatures:
    pattern:  /seeCandidates/{id}
    defaults: { _controller: DTBBdBundle:Candidate:see }
    
dtb_bd_validate_candidature:
    pattern:  /validateCandidate/{id}
    defaults: { _controller: DTBBdBundle:Candidate:validate }
    
dtb_bd_delete_candidature:
    pattern:  /deleteCandidate/{id}
    defaults: { _controller: DTBBdBundle:Candidate:delete }